title: Forward API Documentation
description: Forward stored credentials to third-party APIs securely
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

